name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 20.x, 22.x ]

    steps:
    - name: Use Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean install
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test
